### ISSUE TITLE
How do you send a message such that the "Data messages: Message count" counter increases in the test client?

### ISSUE THREAD

**Issue by AndrewJudson** [mozilla/janus-plugin-sfu#47]
It isn't clear to me how to do this when testing functionality - I can send data messages between clients but it doesn't seem to get handled by the reliable or unreliable channel. Thus I am not sure what the purpose of that part of the test client is and if it is possible to interact with it.

**Comment by mqp** [comment]
Sorry, this was kind of left in a hacky state! In the test client if you try this in the browser REPL:

```javascript
c.publisher.reliableChannel.send('{"foo": 1}')
```

Then other clients should see the data message come in and increment the counter. They try to deserialize it as JSON, so if it doesn't look like JSON they won't bump it.

Happy to accept PRs if you want to make the test client easier to test with. It's obviously not ideal.

**Comment by AndrewJudson** [comment]
Got it, thanks. Is this different than sending it ala `c.publisher.handle.sendMessage({ kind: "data })`?

**Comment by mqp** [comment]
Yes, it's different. There are two different transports:

- The WebRTC data channel to Janus. This has very little logic associated with it; you can send it any string and it will multicast it down the data channel of all other clients in the same room. This is what the "message count" widget currently updates based on -- when it gets a JSON-looking string down the data channel.
- The Janus websocket. This lets you send "messages" (the things whose structure are defined in messages.rs) to Janus, which the plugin will then act on. If you send a "data" kind message (which needs to have the appropriate fields, e.g. `c.publisher.handle.sendMessage({ kind: "data", whom: "783565908", body: "foo" })`), then it will act by pushing out an event to the "whom" user in question containing the body you sent. This could be useful as a substitute for WebRTC data channels in applications where establishing a data channel is not easy, or where you want "private messages". The "message count" widget isn't looking at these.

**Comment by AndrewJudson** [comment]
Hey dumb question - is the reliableChannel over TCP?

**Comment by mqp** [comment]
Nope, all data channels are over SCTP. The properties of the SCTP connection are configured in the client when the channel is created and added to the `RTCPeerConnection`. [In this case](https://github.com/mozilla/janus-plugin-sfu/blob/master/client/tiny.js#L161), `reliableChannel` is named `reliable` because I set `ordered: true` and I didn't set `maxRetransmits: 0`, which mean that it acts like TCP in terms of retrying on failure and ensuring order.

Note that this doesn't necessarily mean that data channel messages will make it to the other users in the room, because even if both channels from the SFU are reliable, there's a missing piece -- if a data channel message makes it to the SFU but then is undeliverable to another user, there isn't currently a mechanism for the SFU to communicate back to the sender that the message wasn't delivered. Someone would need to build that to get end-to-end reliability.
